name: 刷步数

on:
  workflow_dispatch:
    inputs:
      USER:
        description: Zepp账号
        required: true
        type: string
      PWD:
        description: 账号密码
        required: true
        type: string
      FIX_STEP:
        description: 固定步数
        required: true
        type: number

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout codes
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT }}

      - name: 初始化Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: 开始
        env:
            # 优先使用网页传入的参数
            CONFIG: >-
              {
                "USER":"${{ github.event.inputs.USER }}",
                "PWD":"${{ github.event.inputs.PWD }}",
                "FIX_STEP":${{ github.event.inputs.FIX_STEP }},
                "SLEEP_GAP":"5",
                "USE_CONCURRENT":"False"
              }
            AES_KEY: ${{ secrets.AES_KEY }}
        run: |
          pip3 install -r requirements.txt
          python3 main.py

      - name: persist tokens
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add .
          git commit -m "persist tokens trigger by ${{ github.event_name }}"
          git push origin master
